development:
  adapter: postgresql
  encoding: unicode
  database: gereditais_development
  pool: 5
  username: rails
  password: rails
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: gereditais_test
  pool: 5
  username: rails
  password: rails
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: gereditais_production
  pool: 5
  username: rails
  password: rails
  host: localhost
  port: 5432

